title: InterSystems Partner Directory
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  InterSystems Partner Directory is a gallery of applications, solutions, tools, interfaces and adapters built with InterSystems Data Platforms: InterSystems IRIS, Caché, Ensemble, HealthShare, InterSystems IRIS for Health or which help with development, deployment, management and performance tuning for the solutions on Big Data, AI and Machine Learning, Interoperability and Scalability, Health, Finance, Retail
#baseurl: "/docs" # the subpath of your site, e.g. /blog
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://intersystems-community.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://docs.partner.intersystems.com"
# twitter_username: ""
# github_username:  ""

# Build settings
# theme: "just-the-docs"
remote_theme: pmarsceill/just-the-docs

# plugins:
  # - jekyll-feed

logo: "/assets/images/partner_logo.svg"

color_scheme: isc

search_enabled: true
search:
  heading_level: 2
  previews: 3

#aux_links:
#  "GitHub Repo":
#    "https://github.com/intersystems-community/vscode-objectscript"

#footer_content: "Copyright &copy; 2020 InterSystems Corp. Distributed under an <a href=\"https://github.com/intersystems-community/vscode-objectscript/tree/master/LICENSE\">MIT license.</a>"

#ga_tracking: GTM-PKG7GB

  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

